# Generated by Django 6.0.1 on 2026-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradingscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
