# Generated by Django 6.0.1 on 2026-02-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('school', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicDepartment',
            new_name='Department',
        ),
    ]
