# Generated by Django 6.0.1 on 2026-02-13 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('website', models.URLField(null=True)),
                ('reg_number', models.CharField(max_length=15)),
                ('ownership', models.CharField(choices=[('GOVERNMENT', 'government'), ('PRIVATE', 'private'), ('BOTH', 'both')], default='PRIVATE', max_length=10)),
                ('UNEB_No', models.CharField(max_length=15)),
                ('badge', models.ImageField(null=True, upload_to='badges')),
                ('subscription_expiry_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
