# Generated by Django 6.0.1 on 2026-02-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='user',
            new_name='school_admin',
        ),
    ]
