# Generated by Django 6.0.1 on 2026-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_user_schoolprofile_school_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='ownership',
            field=models.CharField(choices=[('GOVERNMENT', 'government'), ('PRIVATE', 'private'), ('OTHERS', 'others')], default='PRIVATE', max_length=10),
        ),
    ]
