# Generated by Django 6.0.1 on 2026-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schoolprofile_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='UNEB_No',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='reg_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
