# Generated by Django 6.0.1 on 2026-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_schoolprofile_uneb_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='motto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
