# Generated by Django 5.2.8 on 2026-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_schoolprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
