# Generated by Django 6.0.1 on 2026-02-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_rename_user_schoolprofile_school_admin'),
        ('staff', '0007_remove_staff_staff_id'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_optional', models.BooleanField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('item_paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feeitem')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.JSONField(default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
    ]
