# Generated by Django 6.0.1 on 2026-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_payment_term_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='payable_amount',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
