# Generated by Django 6.0.1 on 2026-03-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_gradingscale'),
        ('school', '0005_alter_schoolprofile_motto'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('session', models.CharField(max_length=100, null=True)),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.DateTimeField(auto_now_add=True)),
                ('total_attendence', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('session', models.CharField(max_length=100, null=True)),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.DateTimeField(auto_now_add=True)),
                ('total_attendence', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
    ]
