# Generated by Django 6.0.1 on 2026-02-13 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0001_initial'),
        ('departments', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNKNOWN', 'unknown')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('NIN', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(null=True, upload_to='staff_images/')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('alt_phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('emergence_contact_name', models.CharField(max_length=50, null=True)),
                ('emergence_phone', models.CharField(max_length=50, null=True)),
                ('employment_type', models.CharField(choices=[('PART_TIME', 'part-time'), ('FULL_TIME', 'full-time'), ('CONTRACT', 'contract')], max_length=50, null=True)),
                ('contract_start', models.DateField(null=True)),
                ('contract_end', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('reg_number', models.CharField(max_length=50, null=True)),
                ('license_number', models.CharField(max_length=50, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('tin_number', models.CharField(max_length=50, null=True)),
                ('nssf_number', models.CharField(max_length=50, null=True)),
                ('certificate', models.FileField(null=True, upload_to='staff_documents/')),
                ('contract_document', models.FileField(null=True, upload_to='staff_documents/')),
                ('classes_taught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('subjects', models.ManyToManyField(null=True, to='academics.subject')),
                ('teaching_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.academicdepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
