# Generated by Django 6.0.1 on 2026-02-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dep_head'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='staff_user',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='subjects',
            new_name='subjects_taught',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='teaching_department',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
