# Generated by Django 6.0.1 on 2026-02-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_user_staff_staff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
    ]
