# Generated by Django 6.0.1 on 2026-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dep_head'),
        ('staff', '0003_alter_staff_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ManyToManyField(null=True, to='departments.department'),
        ),
    ]
