# Generated by Django 6.0.1 on 2026-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('staff', '0004_remove_staff_department_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='classes_taught',
        ),
        migrations.AddField(
            model_name='staff',
            name='classes_taught',
            field=models.ManyToManyField(null=True, to='classes.classes'),
        ),
    ]
