# Generated by Django 6.0.1 on 2026-02-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_classes_taught_staff_classes_taught'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='departments',
        ),
    ]
