# Generated by Django 6.0.1 on 2026-02-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_department_staff_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
    ]
