# Generated by Django 6.0.1 on 2026-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradingscale'),
        ('classes', '0004_rename_stream_classes_meta_data_remove_classes_block_and_more'),
        ('departments', '0004_alter_department_dep_head'),
        ('staff', '0007_remove_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='NIN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, null=True, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergence_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergence_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('PART_TIME', 'part-time'), ('FULL_TIME', 'full-time'), ('CONTRACT', 'contract')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, null=True, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
