# Generated by Django 6.0.1 on 2026-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staff_nin_alter_staff_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_user',
            new_name='user',
        ),
    ]
