# Generated by Django 5.2.8 on 2026-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_exam_id_alter_gradingscale_id_alter_results_id_and_more'),
        ('classes', '0008_alter_classes_id'),
        ('departments', '0007_alter_department_id'),
        ('staff', '0010_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(blank=True, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, to='academics.subject'),
        ),
    ]
