# Generated by Django 6.0.1 on 2026-02-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classes_block'),
        ('school', '0002_rename_user_schoolprofile_school_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=50, null=True)),
                ('admission_number', models.CharField(max_length=50, null=True)),
                ('stream', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNKNOWN', 'unknown')], max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='students_photos')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('SUSPENDED', 'suspended')], max_length=50)),
                ('guardian_name', models.CharField(max_length=50, null=True)),
                ('guardian_phone', models.CharField(max_length=50)),
                ('guardian_email', models.CharField(max_length=50, null=True)),
                ('relationship', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('allergies', models.CharField(max_length=50, null=True)),
                ('medical_conditions', models.CharField(max_length=50, null=True)),
                ('special_needs', models.CharField(max_length=50, null=True)),
                ('fee_category', models.CharField(max_length=50, null=True)),
                ('boarding_status', models.CharField(choices=[('BOARDING', 'boarding'), ('DAY', 'day'), ('OTHERS', 'others')], max_length=50, null=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile')),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
