# Generated by Django 6.0.1 on 2026-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='special_needs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
