# Generated by Django 6.0.1 on 2026-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentprofile_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'active'), ('SUSPENDED', 'suspended')], max_length=50, null=True),
        ),
    ]
