# Generated by Django 6.0.1 on 2026-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
