# Generated by Django 6.0.1 on 2026-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='block',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
