# Generated by Django 6.0.1 on 2026-03-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classes_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='stream',
            new_name='meta_data',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='block',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_teacher',
        ),
    ]
