# Generated by Django 6.0.1 on 2026-04-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_stream_classes_meta_data_remove_classes_block_and_more'),
        ('staff', '0009_rename_staff_user_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='staff.staff'),
        ),
    ]
