# Generated by Django 5.2.8 on 2026-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classes_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
