name: Schools System CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build react frontend
        working-directory: ./frontend
        run: |
          ls
          npm install
          npm run build

      - name: Setup django
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install django dependencies & test
        working-directory: ./backend
        run: |
          ls
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py test

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build backend docker image
        run: |
          docker build \
            --build-arg SECRET_KEY=${{secrets.SECRET_KEY}}
            --build-arg DATABASE_URL=${{secrets.SCHOOLS_DATABASE_URL}} \
            -t ${{secrets.DOCKER_USERNAME}}/schools-backend ./backend
      
      - name: Push backend image
        run: docker push ${{secrets.DOCKER_USERNAME}}/schools-backend:latest

      - name: Build front end docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/schools-frontend ./frontend

      - name: Push frontend image
        run: docker push ${{secrets.DOCKER_USERNAME}}/schools-frontend:latest