name: School System CI

on:
  push:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Show files
        run: ls

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          cd backend
          python manage.py test

      - name: Verify Node installation
        run: |
          node -v
          npm -v
      - name: Show project structure
        run: |
          ls
          ls frontend
      
      - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '20'
    
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
  
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --watchAll=false
